export default [
    {
        "type": "text",
        "name": "c2",
        "label": "کالا دو",
        // "children": ["1","2"],
        "parent": "parent",
        // "options": [{ value: string | number, title: string | number }],
    },
    {
        "type": "number",
        "name": "c1",
        "label": "کالا یک",
        // "children": ["1","2"],
        "parent": "parent",
        // "options": [{ value: string | number, title: string | number }],
    },
    {
        "type": "number",
        "name": "parent",
        "label": "نام کالا",
        "children": ["c1", "c2"],
        // "parent"?: string,
        // "options": [{ value: string | number, title: string | number }],
    },
    {
        "type": "number",
        "name": "number1",
        "label": "وزن کالاها",
        // "children": ["1","2"],
        // "parent"?: string,
        // "options": [{ value: string | number, title: string | number }],
    },
    {
        "type": "textarea",
        "name": "textarea1",
        "label": "توضیحات",
        // "children": ["1","2"],
        // "parent"?: string,
        // "options": [{ value: string | number, title: string | number }],
    },
    {
        "type": "dropdown",
        "name": "dropdown1",
        "label": "انتخاب تعداد کالا",
        // "children": ["1","2"],
        // "parent"?: string,
        "options": [{ value: 1, title: 100 }, { value: 2, title: 200 }, { value: 3, title: 300 }],
    },
    {
        "type": "checkbox",
        "name": "checkbox1",
        "label": "ارسال فوری",
        // "children": ["1","2"],
        // "parent"?: string,
        // "options": [{ value: string | number, title: string | number }],
    },
    {
        "type": "checkbox-group",
        "name": "checkbox-group",
        "label": "روزهای کاری را انتخاب کنید",
        // "children": ["1","2"],
        // "parent"?: string,
        "options": [{ value: '1', title: 'شنبه' }, { value: '2', title: 'یکشنبه' }, { value: '3', title: 'دوشنبه' }, { value: '4', title: 'سه شنبه' }],
    },
]